config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts
  end
  
  namespace :account do
    resources :groups
    resources :posts
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :owner, class_name: "User", foreign_key: :user_id  
  
  has_many :posts  
  has_many :group_users
  has_many :members, through: :group_users, source: :user

  validates :title, presence: true

  scope :popular, -> { order("posts_count DESC") }

  def editable_by?(user)
    user && user == owner
  end
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User", foreign_key: :user_id
  belongs_to :group, counter_cache: true
  
  validates :content, presence: true

  scope :recent, -> { order("updated_at DESC") }

  def editable_by?(user)
    user && user == author
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :groups
  has_many :posts
  has_many :group_users
  has_many :participated_groups, through: :group_users, source: :group

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end

  def is_member_of?(group)
    participated_groups.include?(group)
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups.popular
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.includes(:group).recent
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    
    if @group.save
      current_user.join!(@group)
      redirect_to groups_path
    else
      render :new      
    end
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def update
    @group = current_user.groups.find(params[:id])

    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end

  def join
    @group = Group.find(params[:id])

    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
    else
      flash[:warning] = "You've already joined this group."
    end

    redirect_to group_path(@group)
    flash[:success] = "Hey #{current_user.name}, Welcome to join us!"
  end

  def quit
    @group = Group.find(params[:id])

    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
    else
      flash[:warning] = "You are not a member of this group."
    end

    redirect_to group_path(@group)
    flash[:success] = "You quit, #{current_user.name}. Hope to see you soon!"
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group
  before_action :member_required, only: [:new, :create]

  def new
    @post = @group.posts.build
  end
  
  def create

    @post = @group.posts.new(post_params)
    @post.author = current_user
    
    if @post.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])

    @post.destroy

    redirect_to group_path(@group)
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def find_group
    @group = Group.find(params[:group_id])
  end

  def member_required
    if !current_user.is_member_of?(@group)
      flash[:warning] = "You are not a member of this group!"
      redirect_to group_path(@group)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def flash_messages
    flash_types          = { success: "success", error: "danger", alert: "warning", notice: "info" }
    close_button_options = { class: "close", "data-dismiss" => "alert" }
    close_button         = content_tag(:button, "×", close_button_options)

    alerts =
      flash.map do |msg_type, message|
        alert_content = close_button + message
        flash_type    = flash_types[msg_type.to_sym] || msg_type
        alert_class   = "alert alert-#{flash_type} alert-dismissible"

        content_tag(:div, alert_content, class: alert_class, role: 'alert')
      end

    alerts.join("\n").html_safe
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_group_updated_at(group)
    group.updated_at.to_s(:long)
  end

  def render_group_title(group)
    truncate(group.title, length: 25)
  end

  def render_group_manage_button(group)
    if current_user && group.editable_by?(current_user)
      link_to("Edit", edit_group_path(group), class: "btn btn-mini") +
      link_to("Delete", group_path(group), class: "btn btn-mini", method: :delete, data: { confirm: "Are you sure???" })
    end
  end

  def render_group_join_quit_button(group)
    if current_user.is_member_of?(@group)
      link_to("Quit Group", quit_group_path(@group), method: :post, class: "btn btn-md btn-warning")
    else
      link_to("Join Group", join_group_path(@group), method: :post, class: "btn btn-md btn-warning")
    end
  end

  def render_new_post_button_of_group(group)
    if current_user.is_member_of?(group)
      link_to("New Post", new_group_post_path(@group), class: "btn btn-md btn-default")
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_post_updated_at(post)
    post.updated_at.to_s(:long)
  end

  def render_post_content(post)
    simple_format(post.content)
  end

  def render_post_manage_button(group, post)
    if current_user && post.editable_by?(current_user)
      link_to("Edit", edit_group_post_path(post.group, post), class: "btn btn-sm") +
      link_to("Delete", group_post_path(post.group, post), class: "btn btn-sm", method: :delete, data: { confirm: "Are you sure???" }) 
    end
  end
end

app/views/groups/_auth.html.erb
<div class="authorization">
  <% if !current_user %>
    <%= link_to("Sign In", new_user_session_path, class: "btn btn-info") %>
    <%= link_to("Registration", new_user_registration_path, class: "btn btn-info") %>
  <% else %>
    <%= link_to("Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-info") %>
    <%= link_to("My Group", account_groups_path, class: "btn btn-warning") %>
    <%= link_to("My Post", account_posts_path, class: "btn btn-warning") %>
  <% end %>
</div>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <%= f.input :title, input_html: { class: "input-xxlarge" } %>
  <%= f.input :description, input_html: { class: "input-xxlarge" } %>
  
  <div class="form-actions">
    <%= f.submit "Submit", disable_with: 'Submitting...', class: "btn btn-md btn-default" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="col-sm-10 col-sm-offset-1">
  
  <%= render "form" %>

</div>

app/views/groups/index.html.erb
<div class="col-xs-12">
  <%= render "auth" %>
  
  <div class="group">
    <%= link_to("New Group", new_group_path, class: "btn btn-mini btn-default pull-right") %>
  </div>
  
  <div class="test">Test if "Touch restart.txt" works!!!!!!!!!!!!!</div>

  <table class="table">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(render_group_title(group), group_path(group)) %></td>
          <td><%= group.description %></td>
          <td><%= render_group_manage_button(group) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-sm-10 col-sm-offset-1">
  
  <%= render "form" %>

</div>

app/views/groups/show.html.erb
<div class="col-sm-10 col-sm-offset-1">
  <%= render "auth" %>
  
  <% if current_user %>
    <div class="member-or-not pull-right">
      <%= render_group_join_quit_button(@group) %>
    </div>
  
    <div class="group pull-right">
      <%= render_group_manage_button(@group) %>
      <%= render_new_post_button_of_group(@group) %>
    </div>
  <% end %>

  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>

  <table class="table">
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <span class="author"><strong>Author: <%= post.author.name %></strong></span>
            <p><%= render_post_content(post) %></p>
          </td>
          <td><%= render_post_manage_button(@group, post) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Training</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash_messages %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for [@group, @post] do |f| %>
  <%= f.input :content, input_html: { class: "input-xxlarge" } %>

  <div class="form-actions">
    <%= f.submit "Submit", disable_with: "Submitting...", class: "btn btn-default" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="col-xs-10 col-xs-offset-1">

  <%= render "form" %>

</div>

app/views/posts/new.html.erb
<div class="col-xs-10 col-xs-offset-1">

  <%= render "form" %>

</div>